### ISSUE TITLE
User-specified structure/supercell?

### ISSUE THREAD

**Issue by DS-Wen** [pydii/pydii#3]
Hi developers, I wonder if it is possible to use structures/supercells built by users? It seems to me that mpid is necessary to start a project. 

Thanks,
Dongsheng

**Comment by mbkumar** [comment]
Reading structures from users is not implemented, but it is not difficult to do. I'll do it this weekend.

**Comment by ganesh028** [comment]
Hi developers, I wonder whether you already finished the above request i.e. reading structures and energies from the users.

**Comment by mbkumar** [comment]
The functionality of user specified structures is available now with optional --struct keyword. Please run the scripts with -h option to learn more about using --struct keyword

Unfortunately I couldn't fully test this because I don't have access to VASP anymore.

**Comment by DS-Wen** [comment]
Thank you,
I am working on the codes ```gen_def_structure``` and ```gen_sol_site_pref``` to generate some user-specified structures for vasp calculations. And I will see if my modifications are working. If it works I will make a pull request.

**Comment by enze-chen** [comment]
OK @mbkumar I submitted a PR where I checked your fixes. Looks good! Only a few small typos, but it seems to handle the user input file cleanly. Updated the docs to specify what files were allowed. I also compared the calculated concentrations to one set of my previous calculations and the numbers match, even with the new file format. Could you look over my changes and merge?

@DS-Wen @ganesh028  I hope this helps. If you find issues with user input files, please let us know.

#4 seems like a trickier fix, as is HCP in general. 😛  Should be able to take a look later this week.

**Comment by ganesh028** [comment]
Thank you very much. I will check it out with my VASP input file.

**Comment by mbkumar** [comment]
Thanks Enze for the cleanup. I am closing this. If anyone finds bugs with updated code, open a new issue.
